# Generated by Django 5.2.3 on 2025-06-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='salary_per_day',
            field=models.DecimalField(decimal_places=2, default='2000', max_digits=100),
        ),
    ]
