# Generated by Django 5.2.3 on 2025-06-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_salary_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employment_start_date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='salary_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
