# Generated by Django 5.2.3 on 2025-06-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_employment_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employment_start_date',
            field=models.DateField(),
        ),
    ]
