# Generated by Django 5.2.3 on 2025-06-27 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_employment_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='employment_start_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='salary_per_day',
        ),
    ]
